version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    # labels: []
    schedule:
      interval: "daily"
      time: "21:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    # labels: []
    schedule:
      interval: "daily"
      time: "21:00"
    open-pull-requests-limit: 10
