name: Setup Sccache

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('SCCACHE_GHA_ENABLED', 'true');

    - uses: mozilla-actions/sccache-action@v0.0.3

    - shell: bash
      run: |
        sccache --stop-server || true
